name: build and publish

on:
  push:
    branches:
      - main
    tags:
      - '*'

env:
  TERM: xterm-256color

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          repository: yukimochi/Activity-Relay
          ref: ${{ github.ref_name }}
          fetch-depth: 0
          path: upstream

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x

      - name: Run GoReleaser
        if: startsWith(github.ref, 'refs/tags/')
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
